from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fcd97be6d79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo_members', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('ARCHITECT', 'CONTRIBUTOR', 'EXECUTOR', 'BLACKBOX_TESTER', 'OBSERVER', name='reporole'),
               existing_nullable=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('ARCHITECT', 'CONTRIBUTOR', 'EXECUTOR', 'BLACKBOX_TESTER', 'OBSERVER', name='reporole'),
               existing_nullable=False)

    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_repo_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.drop_column('is_global')
        batch_op.drop_column('allowed_repo_ids')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ARCHITECT', 'CONTRIBUTOR', 'EXECUTOR', 'BLACKBOX_TESTER', 'OBSERVER', name='reporole'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('repo_members', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ARCHITECT', 'CONTRIBUTOR', 'EXECUTOR', 'BLACKBOX_TESTER', 'OBSERVER', name='reporole'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
