"""baseline_v2_canonical

Revision ID: c6274e9707ba
Revises:
Create Date: 2026-03-19 16:40:43.231781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6274e9707ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=12), nullable=False),
    sa.Column('claim_code', sa.String(length=8), nullable=False),
    sa.Column('claim_url', sa.String(length=255), nullable=False),
    sa.Column('claim_expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFYING', 'CLAIMED', 'SUSPENDED', 'EXPIRED', name='agentstatus'), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('preferred_tracks', sa.JSON(), nullable=True),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('owner_github_id', sa.String(length=50), nullable=True),
    sa.Column('owner_github_login', sa.String(length=100), nullable=True),
    sa.Column('owner_wechat_openid', sa.String(length=100), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_count', sa.Integer(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('validation_violations', sa.Integer(), nullable=False),
    sa.Column('suspended_until', sa.DateTime(), nullable=True),
    sa.Column('last_violation_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_claim_code'), 'agents', ['claim_code'], unique=True)
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_agent_id'), 'auditlog', ['agent_id'], unique=False)
    op.create_index(op.f('ix_auditlog_repo_name'), 'auditlog', ['repo_name'], unique=False)
    op.create_index(op.f('ix_auditlog_timestamp'), 'auditlog', ['timestamp'], unique=False)
    op.create_table('bounty',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=True),
    sa.Column('required_role', sa.Enum('architect', 'contributor', 'reviewer', 'executor', 'tester', 'librarian', 'observer', name='repo_role', native_enum=False), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('track', sa.String(), nullable=True),
    sa.Column('is_temporary_claim', sa.Boolean(), nullable=False),
    sa.Column('claim_expires_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_by_user_id', sa.String(), nullable=True),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('current_steps', sa.Integer(), nullable=False),
    sa.Column('context_files', sa.JSON(), nullable=True),
    sa.Column('target_files', sa.JSON(), nullable=True),
    sa.Column('acceptance_criteria', sa.String(), nullable=True),
    sa.Column('test_command', sa.String(), nullable=False),
    sa.Column('verification_mode', sa.String(), nullable=False),
    sa.Column('preparation_notes', sa.JSON(), nullable=True),
    sa.Column('cancelled_by', sa.String(), nullable=True),
    sa.Column('cancelled_reason', sa.String(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounty_assignee'), 'bounty', ['assignee'], unique=False)
    op.create_index(op.f('ix_bounty_cancelled_at'), 'bounty', ['cancelled_at'], unique=False)
    op.create_index(op.f('ix_bounty_cancelled_by'), 'bounty', ['cancelled_by'], unique=False)
    op.create_index(op.f('ix_bounty_claim_expires_at'), 'bounty', ['claim_expires_at'], unique=False)
    op.create_index(op.f('ix_bounty_claimed_by_user_id'), 'bounty', ['claimed_by_user_id'], unique=False)
    op.create_index(op.f('ix_bounty_parent_id'), 'bounty', ['parent_id'], unique=False)
    op.create_index(op.f('ix_bounty_repo_id'), 'bounty', ['repo_id'], unique=False)
    op.create_index(op.f('ix_bounty_repo_name'), 'bounty', ['repo_name'], unique=False)
    op.create_index(op.f('ix_bounty_status'), 'bounty', ['status'], unique=False)
    op.create_index(op.f('ix_bounty_title'), 'bounty', ['title'], unique=False)
    op.create_index(op.f('ix_bounty_track'), 'bounty', ['track'], unique=False)
    op.create_table('commitrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('bounty_id', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('intent_category', sa.String(), nullable=False),
    sa.Column('intent_description', sa.String(), nullable=False),
    sa.Column('diff_summary', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('verification_exit_code', sa.Integer(), nullable=True),
    sa.Column('verification_stdout', sa.String(), nullable=True),
    sa.Column('trace_json', sa.JSON(), nullable=True),
    sa.Column('blackbox_status', sa.String(), nullable=False),
    sa.Column('blackbox_report', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitrecord_agent_id'), 'commitrecord', ['agent_id'], unique=False)
    op.create_index(op.f('ix_commitrecord_bounty_id'), 'commitrecord', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_commitrecord_branch_name'), 'commitrecord', ['branch_name'], unique=False)
    op.create_index(op.f('ix_commitrecord_commit_sha'), 'commitrecord', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_commitrecord_repo_name'), 'commitrecord', ['repo_name'], unique=False)
    op.create_index(op.f('ix_commitrecord_status'), 'commitrecord', ['status'], unique=False)
    op.create_table('compute_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bounty_id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=True),
    sa.Column('submission_id', sa.String(), nullable=True),
    sa.Column('runner_id', sa.Uuid(), nullable=True),
    sa.Column('execution_mode', sa.Enum('SHARED_LOCAL', 'YOLO_MODE', 'SELF_HOSTED', name='executionmode'), nullable=False),
    sa.Column('requester_user_id', sa.Uuid(), nullable=True),
    sa.Column('requester_agent_id', sa.Uuid(), nullable=True),
    sa.Column('requester_type', sa.String(length=20), nullable=True),
    sa.Column('test_command', sa.String(length=500), nullable=False),
    sa.Column('code_url', sa.String(length=500), nullable=True),
    sa.Column('code_branch', sa.String(length=100), nullable=True),
    sa.Column('code_commit', sa.String(length=40), nullable=True),
    sa.Column('env_vars', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT', 'AUDIT_FAILED', 'PARTIAL_PASS', 'HUMAN_REVIEW', name='computejobstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout_log', sa.Text(), nullable=True),
    sa.Column('stderr_log', sa.Text(), nullable=True),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('retry_backoff_factor', sa.Float(), nullable=False),
    sa.Column('retry_base_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('skipped_tests', sa.Integer(), nullable=False),
    sa.Column('partial_pass_threshold', sa.Float(), nullable=False),
    sa.Column('failure_severity', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('original_runner_id', sa.Uuid(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('is_audited', sa.Boolean(), nullable=False),
    sa.Column('audit_job_id', sa.Uuid(), nullable=True),
    sa.Column('audit_result', sa.String(length=50), nullable=True),
    sa.Column('audit_mismatch_details', sa.Text(), nullable=True),
    sa.Column('service_endpoint', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compute_jobs_bounty_id'), 'compute_jobs', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_compute_jobs_repo_id'), 'compute_jobs', ['repo_id'], unique=False)
    op.create_index(op.f('ix_compute_jobs_requester_agent_id'), 'compute_jobs', ['requester_agent_id'], unique=False)
    op.create_index(op.f('ix_compute_jobs_requester_user_id'), 'compute_jobs', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_compute_jobs_runner_id'), 'compute_jobs', ['runner_id'], unique=False)
    op.create_index(op.f('ix_compute_jobs_status'), 'compute_jobs', ['status'], unique=False)
    op.create_table('meta_repo_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('deploy_root', sa.String(), nullable=False),
    sa.Column('current_commit', sa.String(), nullable=True),
    sa.Column('last_deploy_at', sa.DateTime(), nullable=True),
    sa.Column('hot_reload_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_restart_services', sa.JSON(), nullable=True),
    sa.Column('require_approval_count', sa.Integer(), nullable=False),
    sa.Column('require_human_approval', sa.Boolean(), nullable=False),
    sa.Column('protected_paths', sa.JSON(), nullable=True),
    sa.Column('allow_direct_push', sa.Boolean(), nullable=False),
    sa.Column('require_fork_workflow', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name')
    )
    op.create_table('meta_repo_forks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fork_name', sa.String(), nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('source_commit', sa.String(), nullable=False),
    sa.Column('last_sync_commit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_repo_forks_fork_name'), 'meta_repo_forks', ['fork_name'], unique=True)
    op.create_index(op.f('ix_meta_repo_forks_owner_id'), 'meta_repo_forks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_meta_repo_forks_owner_type'), 'meta_repo_forks', ['owner_type'], unique=False)
    op.create_index(op.f('ix_meta_repo_forks_status'), 'meta_repo_forks', ['status'], unique=False)
    op.create_table('platform_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_audit_log_actor_id'), 'platform_audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_actor_type'), 'platform_audit_log', ['actor_type'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_event_type'), 'platform_audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_target_id'), 'platform_audit_log', ['target_id'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_target_type'), 'platform_audit_log', ['target_type'], unique=False)
    op.create_index(op.f('ix_platform_audit_log_timestamp'), 'platform_audit_log', ['timestamp'], unique=False)
    op.create_table('platform_prs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_branch', sa.String(), nullable=False),
    sa.Column('source_repo', sa.String(), nullable=False),
    sa.Column('target_branch', sa.String(), nullable=False),
    sa.Column('author_type', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('author_github_login', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('touches_protected_paths', sa.Boolean(), nullable=False),
    sa.Column('requires_elevated_review', sa.Boolean(), nullable=False),
    sa.Column('approvals', sa.JSON(), nullable=True),
    sa.Column('approval_count', sa.Integer(), nullable=False),
    sa.Column('required_approval_count', sa.Integer(), nullable=False),
    sa.Column('verification_passed', sa.Boolean(), nullable=True),
    sa.Column('verification_log', sa.String(), nullable=True),
    sa.Column('update_id', sa.Integer(), nullable=True),
    sa.Column('merge_commit_sha', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_prs_author_id'), 'platform_prs', ['author_id'], unique=False)
    op.create_index(op.f('ix_platform_prs_author_type'), 'platform_prs', ['author_type'], unique=False)
    op.create_index(op.f('ix_platform_prs_pr_number'), 'platform_prs', ['pr_number'], unique=True)
    op.create_index(op.f('ix_platform_prs_status'), 'platform_prs', ['status'], unique=False)
    op.create_table('skill_async_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('args_hash', sa.String(), nullable=True),
    sa.Column('result_hash', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_skill_async_jobs_actor_id'), 'skill_async_jobs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_skill_async_jobs_args_hash'), 'skill_async_jobs', ['args_hash'], unique=False)
    op.create_index(op.f('ix_skill_async_jobs_created_at'), 'skill_async_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_skill_async_jobs_finished_at'), 'skill_async_jobs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_skill_async_jobs_result_hash'), 'skill_async_jobs', ['result_hash'], unique=False)
    op.create_index(op.f('ix_skill_async_jobs_skill_name'), 'skill_async_jobs', ['skill_name'], unique=False)
    op.create_index(op.f('ix_skill_async_jobs_started_at'), 'skill_async_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_skill_async_jobs_status'), 'skill_async_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_skill_async_jobs_trace_id'), 'skill_async_jobs', ['trace_id'], unique=False)
    op.create_table('platform_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_pr_id', sa.Integer(), nullable=True),
    sa.Column('source_pr_number', sa.Integer(), nullable=True),
    sa.Column('source_commit_sha', sa.String(), nullable=False),
    sa.Column('source_branch', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('files_changed', sa.JSON(), nullable=True),
    sa.Column('files_synced', sa.JSON(), nullable=True),
    sa.Column('files_failed', sa.JSON(), nullable=True),
    sa.Column('pre_deploy_health', sa.Text(), nullable=True),
    sa.Column('post_deploy_health', sa.Text(), nullable=True),
    sa.Column('previous_commit_sha', sa.String(), nullable=True),
    sa.Column('rollback_available', sa.Boolean(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('deploy_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_updates_previous_commit_sha'), 'platform_updates', ['previous_commit_sha'], unique=False)
    op.create_index(op.f('ix_platform_updates_source_commit_sha'), 'platform_updates', ['source_commit_sha'], unique=False)
    op.create_index(op.f('ix_platform_updates_source_pr_id'), 'platform_updates', ['source_pr_id'], unique=False)
    op.create_index(op.f('ix_platform_updates_source_pr_number'), 'platform_updates', ['source_pr_number'], unique=False)
    op.create_index(op.f('ix_platform_updates_status'), 'platform_updates', ['status'], unique=False)
    op.create_table('repoconfig',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('lock_mode', sa.String(), nullable=False),
    sa.Column('locked_branches', sa.JSON(), nullable=True),
    sa.Column('locked_paths', sa.JSON(), nullable=True),
    sa.Column('default_permission', sa.String(), nullable=False),
    sa.Column('collaborators', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('allow_force_push', sa.Boolean(), nullable=False),
    sa.Column('require_trace_commit', sa.Boolean(), nullable=False),
    sa.Column('branch_protection', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repoconfig_name'), 'repoconfig', ['name'], unique=True)
    op.create_index(op.f('ix_repoconfig_owner_id'), 'repoconfig', ['owner_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ARCHITECT', 'CONTRIBUTOR', 'REVIEWER', 'EXECUTOR', 'BLACKBOX_TESTER', 'LIBRARIAN', 'OBSERVER', name='reporole'), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('github_id', sa.String(length=50), nullable=True),
    sa.Column('github_login', sa.String(length=100), nullable=True),
    sa.Column('github_avatar', sa.String(length=500), nullable=True),
    sa.Column('wechat_openid', sa.String(length=100), nullable=True),
    sa.Column('wechat_nickname', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=False)
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=False)
    op.create_table('agent_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('total_tasks_assigned', sa.Integer(), nullable=False),
    sa.Column('total_tasks_completed', sa.Integer(), nullable=False),
    sa.Column('total_tasks_failed', sa.Integer(), nullable=False),
    sa.Column('total_tasks_cancelled', sa.Integer(), nullable=False),
    sa.Column('total_completion_time_hours', sa.Float(), nullable=False),
    sa.Column('avg_completion_time_hours', sa.Float(), nullable=True),
    sa.Column('total_quality_score', sa.Float(), nullable=False),
    sa.Column('avg_quality_score', sa.Float(), nullable=True),
    sa.Column('first_attempt_success_rate', sa.Float(), nullable=True),
    sa.Column('response_times_json', sa.Text(), nullable=True),
    sa.Column('response_time_p50_hours', sa.Float(), nullable=True),
    sa.Column('response_time_p95_hours', sa.Float(), nullable=True),
    sa.Column('track_performance_json', sa.Text(), nullable=True),
    sa.Column('skill_performance_json', sa.Text(), nullable=True),
    sa.Column('current_active_tasks', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('reliability_tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_task_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_metrics_agent_id'), 'agent_metrics', ['agent_id'], unique=True)
    op.create_table('email_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_table('repos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('webhook_secret', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_created_by_user_id'), 'repos', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_repos_full_name'), 'repos', ['full_name'], unique=True)
    op.create_index(op.f('ix_repos_github_repo_id'), 'repos', ['github_repo_id'], unique=False)
    op.create_table('runner_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_runner_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runner_tokens_is_used'), 'runner_tokens', ['is_used'], unique=False)
    op.create_index(op.f('ix_runner_tokens_token'), 'runner_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_runner_tokens_user_id'), 'runner_tokens', ['user_id'], unique=False)
    op.create_table('runners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'BUSY', 'DISABLED', 'BANNED', name='runnerstatus'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_ip', sa.String(length=45), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('memory_gb', sa.Integer(), nullable=True),
    sa.Column('os_type', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('docker_version', sa.String(length=50), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('pool_type', sa.Enum('PRIVATE', 'SHARED', 'PLATFORM', name='runnerpooltype'), nullable=False),
    sa.Column('allowed_repo_ids', sa.JSON(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('total_jobs_completed', sa.Integer(), nullable=False),
    sa.Column('total_jobs_failed', sa.Integer(), nullable=False),
    sa.Column('total_compute_seconds', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Integer(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('audit_failures', sa.Integer(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('banned_reason', sa.String(length=500), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('current_job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runners_owner_user_id'), 'runners', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_runners_pool_type'), 'runners', ['pool_type'], unique=False)
    op.create_index(op.f('ix_runners_status'), 'runners', ['status'], unique=False)
    op.create_table('runner_share_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('runner_id', sa.Uuid(), nullable=False),
    sa.Column('grantee_user_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('can_execute', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grantee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runner_id', 'grantee_user_id', name='uq_runner_share_runner_grantee')
    )
    op.create_index(op.f('ix_runner_share_grants_granted_by_user_id'), 'runner_share_grants', ['granted_by_user_id'], unique=False)
    op.create_index(op.f('ix_runner_share_grants_grantee_user_id'), 'runner_share_grants', ['grantee_user_id'], unique=False)
    op.create_index(op.f('ix_runner_share_grants_runner_id'), 'runner_share_grants', ['runner_id'], unique=False)
    op.create_table('user_agent_bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('bound_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', name='uq_binding_agent'),
    sa.UniqueConstraint('user_id', name='uq_binding_user')
    )
    op.create_index(op.f('ix_user_agent_bindings_agent_id'), 'user_agent_bindings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_user_agent_bindings_user_id'), 'user_agent_bindings', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('runner_id', sa.Uuid(), nullable=False),
    sa.Column('original_stdout', sa.Text(), nullable=True),
    sa.Column('original_exit_code', sa.Integer(), nullable=True),
    sa.Column('original_passed', sa.Boolean(), nullable=True),
    sa.Column('audited_stdout', sa.Text(), nullable=True),
    sa.Column('audited_exit_code', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.Enum('PASSED', 'FAILED', 'SUSPICIOUS', name='auditresult'), nullable=True),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['compute_jobs.id'], ),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_job_id'), 'audit_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_runner_id'), 'audit_logs', ['runner_id'], unique=False)
    op.create_table('repo_execution_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('execution_mode', sa.Enum('SHARED_LOCAL', 'YOLO_MODE', 'SELF_HOSTED', name='executionmode'), nullable=False),
    sa.Column('preferred_runner_ids', sa.JSON(), nullable=True),
    sa.Column('sponsor_user_id', sa.Uuid(), nullable=True),
    sa.Column('budget_limit', sa.Integer(), nullable=False),
    sa.Column('yolo_require_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_execution_configs_repo_id'), 'repo_execution_configs', ['repo_id'], unique=True)
    op.create_table('repo_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ARCHITECT', 'CONTRIBUTOR', 'REVIEWER', 'EXECUTOR', 'BLACKBOX_TESTER', 'LIBRARIAN', 'OBSERVER', name='reporole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', name='membershipstatus'), nullable=False),
    sa.Column('added_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('kicked_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('kicked_at', sa.DateTime(), nullable=True),
    sa.Column('kick_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'agent_id', name='uq_repo_agent')
    )
    op.create_index(op.f('ix_repo_members_agent_id'), 'repo_members', ['agent_id'], unique=False)
    op.create_index(op.f('ix_repo_members_repo_id'), 'repo_members', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repo_members_repo_id'), table_name='repo_members')
    op.drop_index(op.f('ix_repo_members_agent_id'), table_name='repo_members')
    op.drop_table('repo_members')
    op.drop_index(op.f('ix_repo_execution_configs_repo_id'), table_name='repo_execution_configs')
    op.drop_table('repo_execution_configs')
    op.drop_index(op.f('ix_audit_logs_runner_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_job_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_user_agent_bindings_user_id'), table_name='user_agent_bindings')
    op.drop_index(op.f('ix_user_agent_bindings_agent_id'), table_name='user_agent_bindings')
    op.drop_table('user_agent_bindings')
    op.drop_index(op.f('ix_runner_share_grants_runner_id'), table_name='runner_share_grants')
    op.drop_index(op.f('ix_runner_share_grants_grantee_user_id'), table_name='runner_share_grants')
    op.drop_index(op.f('ix_runner_share_grants_granted_by_user_id'), table_name='runner_share_grants')
    op.drop_table('runner_share_grants')
    op.drop_index(op.f('ix_runners_status'), table_name='runners')
    op.drop_index(op.f('ix_runners_pool_type'), table_name='runners')
    op.drop_index(op.f('ix_runners_owner_user_id'), table_name='runners')
    op.drop_table('runners')
    op.drop_index(op.f('ix_runner_tokens_user_id'), table_name='runner_tokens')
    op.drop_index(op.f('ix_runner_tokens_token'), table_name='runner_tokens')
    op.drop_index(op.f('ix_runner_tokens_is_used'), table_name='runner_tokens')
    op.drop_table('runner_tokens')
    op.drop_index(op.f('ix_repos_github_repo_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_full_name'), table_name='repos')
    op.drop_index(op.f('ix_repos_created_by_user_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_agent_metrics_agent_id'), table_name='agent_metrics')
    op.drop_table('agent_metrics')
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_repoconfig_owner_id'), table_name='repoconfig')
    op.drop_index(op.f('ix_repoconfig_name'), table_name='repoconfig')
    op.drop_table('repoconfig')
    op.drop_index(op.f('ix_platform_updates_status'), table_name='platform_updates')
    op.drop_index(op.f('ix_platform_updates_source_pr_number'), table_name='platform_updates')
    op.drop_index(op.f('ix_platform_updates_source_pr_id'), table_name='platform_updates')
    op.drop_index(op.f('ix_platform_updates_source_commit_sha'), table_name='platform_updates')
    op.drop_index(op.f('ix_platform_updates_previous_commit_sha'), table_name='platform_updates')
    op.drop_table('platform_updates')
    op.drop_index(op.f('ix_skill_async_jobs_trace_id'), table_name='skill_async_jobs')
    op.drop_index(op.f('ix_skill_async_jobs_status'), table_name='skill_async_jobs')
    op.drop_index(op.f('ix_skill_async_jobs_started_at'), table_name='skill_async_jobs')
    op.drop_index(op.f('ix_skill_async_jobs_skill_name'), table_name='skill_async_jobs')
    op.drop_index(op.f('ix_skill_async_jobs_result_hash'), table_name='skill_async_jobs')
    op.drop_index(op.f('ix_skill_async_jobs_finished_at'), table_name='skill_async_jobs')
    op.drop_index(op.f('ix_skill_async_jobs_created_at'), table_name='skill_async_jobs')
    op.drop_index(op.f('ix_skill_async_jobs_args_hash'), table_name='skill_async_jobs')
    op.drop_index(op.f('ix_skill_async_jobs_actor_id'), table_name='skill_async_jobs')
    op.drop_table('skill_async_jobs')
    op.drop_index(op.f('ix_platform_prs_status'), table_name='platform_prs')
    op.drop_index(op.f('ix_platform_prs_pr_number'), table_name='platform_prs')
    op.drop_index(op.f('ix_platform_prs_author_type'), table_name='platform_prs')
    op.drop_index(op.f('ix_platform_prs_author_id'), table_name='platform_prs')
    op.drop_table('platform_prs')
    op.drop_index(op.f('ix_platform_audit_log_timestamp'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_target_type'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_target_id'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_event_type'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_actor_type'), table_name='platform_audit_log')
    op.drop_index(op.f('ix_platform_audit_log_actor_id'), table_name='platform_audit_log')
    op.drop_table('platform_audit_log')
    op.drop_index(op.f('ix_meta_repo_forks_status'), table_name='meta_repo_forks')
    op.drop_index(op.f('ix_meta_repo_forks_owner_type'), table_name='meta_repo_forks')
    op.drop_index(op.f('ix_meta_repo_forks_owner_id'), table_name='meta_repo_forks')
    op.drop_index(op.f('ix_meta_repo_forks_fork_name'), table_name='meta_repo_forks')
    op.drop_table('meta_repo_forks')
    op.drop_table('meta_repo_config')
    op.drop_index(op.f('ix_compute_jobs_status'), table_name='compute_jobs')
    op.drop_index(op.f('ix_compute_jobs_runner_id'), table_name='compute_jobs')
    op.drop_index(op.f('ix_compute_jobs_requester_user_id'), table_name='compute_jobs')
    op.drop_index(op.f('ix_compute_jobs_requester_agent_id'), table_name='compute_jobs')
    op.drop_index(op.f('ix_compute_jobs_repo_id'), table_name='compute_jobs')
    op.drop_index(op.f('ix_compute_jobs_bounty_id'), table_name='compute_jobs')
    op.drop_table('compute_jobs')
    op.drop_index(op.f('ix_commitrecord_status'), table_name='commitrecord')
    op.drop_index(op.f('ix_commitrecord_repo_name'), table_name='commitrecord')
    op.drop_index(op.f('ix_commitrecord_commit_sha'), table_name='commitrecord')
    op.drop_index(op.f('ix_commitrecord_branch_name'), table_name='commitrecord')
    op.drop_index(op.f('ix_commitrecord_bounty_id'), table_name='commitrecord')
    op.drop_index(op.f('ix_commitrecord_agent_id'), table_name='commitrecord')
    op.drop_table('commitrecord')
    op.drop_index(op.f('ix_bounty_track'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_title'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_status'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_repo_name'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_repo_id'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_parent_id'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_claimed_by_user_id'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_claim_expires_at'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_cancelled_by'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_cancelled_at'), table_name='bounty')
    op.drop_index(op.f('ix_bounty_assignee'), table_name='bounty')
    op.drop_table('bounty')
    op.drop_index(op.f('ix_auditlog_timestamp'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_repo_name'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_agent_id'), table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_agents_claim_code'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
