"""sync_models_to_database

Revision ID: e7da0f12cfd1
Revises: 5fcd97be6d79
Create Date: 2026-03-16 13:56:31.465407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e7da0f12cfd1'
down_revision: Union[str, Sequence[str], None] = '5fcd97be6d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runners_owner_user_id'), table_name='runners')
    op.drop_index(op.f('ix_runners_status'), table_name='runners')
    op.drop_table('runners')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_compute_jobs_bounty_id'), table_name='compute_jobs')
    op.drop_index(op.f('ix_compute_jobs_repo_id'), table_name='compute_jobs')
    op.drop_index(op.f('ix_compute_jobs_runner_id'), table_name='compute_jobs')
    op.drop_index(op.f('ix_compute_jobs_status'), table_name='compute_jobs')
    op.drop_table('compute_jobs')
    op.drop_index(op.f('ix_repo_members_agent_id'), table_name='repo_members')
    op.drop_index(op.f('ix_repo_members_repo_id'), table_name='repo_members')
    op.drop_table('repo_members')
    op.drop_index(op.f('ix_repos_created_by_user_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_full_name'), table_name='repos')
    op.drop_index(op.f('ix_repos_github_repo_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_repo_execution_configs_repo_id'), table_name='repo_execution_configs')
    op.drop_table('repo_execution_configs')
    op.drop_index(op.f('ix_runner_tokens_is_used'), table_name='runner_tokens')
    op.drop_index(op.f('ix_runner_tokens_token'), table_name='runner_tokens')
    op.drop_index(op.f('ix_runner_tokens_user_id'), table_name='runner_tokens')
    op.drop_table('runner_tokens')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_audit_logs_job_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_runner_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_user_agent_bindings_agent_id'), table_name='user_agent_bindings')
    op.drop_index(op.f('ix_user_agent_bindings_user_id'), table_name='user_agent_bindings')
    op.drop_table('user_agent_bindings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agent_bindings',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('agent_id', sa.CHAR(length=32), nullable=False),
    sa.Column('bound_at', sa.DATETIME(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('is_permanent', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', name=op.f('uq_binding_agent')),
    sa.UniqueConstraint('user_id', name=op.f('uq_binding_user'))
    )
    op.create_index(op.f('ix_user_agent_bindings_user_id'), 'user_agent_bindings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_agent_bindings_agent_id'), 'user_agent_bindings', ['agent_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('job_id', sa.CHAR(length=32), nullable=False),
    sa.Column('runner_id', sa.CHAR(length=32), nullable=False),
    sa.Column('original_stdout', sa.TEXT(), nullable=True),
    sa.Column('original_exit_code', sa.INTEGER(), nullable=True),
    sa.Column('original_passed', sa.BOOLEAN(), nullable=True),
    sa.Column('audited_stdout', sa.TEXT(), nullable=True),
    sa.Column('audited_exit_code', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('result', sa.VARCHAR(length=10), nullable=True),
    sa.Column('explanation', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=100), nullable=False),
    sa.Column('audited_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['compute_jobs.id'], ),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_runner_id'), 'audit_logs', ['runner_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_job_id'), 'audit_logs', ['job_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('role', sa.VARCHAR(length=15), nullable=False),
    sa.Column('permission', sa.VARCHAR(length=100), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('max_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission', name=op.f('uq_role_permission'))
    )
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('runner_tokens',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('used_by_runner_id', sa.CHAR(length=32), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_ip', sa.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runner_tokens_user_id'), 'runner_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_runner_tokens_token'), 'runner_tokens', ['token'], unique=1)
    op.create_index(op.f('ix_runner_tokens_is_used'), 'runner_tokens', ['is_used'], unique=False)
    op.create_table('repo_execution_configs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('repo_id', sa.CHAR(length=32), nullable=False),
    sa.Column('execution_mode', sa.VARCHAR(length=12), nullable=False),
    sa.Column('preferred_runner_ids', sqlite.JSON(), nullable=True),
    sa.Column('sponsor_user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('yolo_require_human_review', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('budget_limit', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_execution_configs_repo_id'), 'repo_execution_configs', ['repo_id'], unique=1)
    op.create_table('repos',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('github_repo_id', sa.INTEGER(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('owner', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_by_user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_private', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('webhook_secret', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_github_repo_id'), 'repos', ['github_repo_id'], unique=False)
    op.create_index(op.f('ix_repos_full_name'), 'repos', ['full_name'], unique=1)
    op.create_index(op.f('ix_repos_created_by_user_id'), 'repos', ['created_by_user_id'], unique=False)
    op.create_table('repo_members',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('repo_id', sa.CHAR(length=32), nullable=False),
    sa.Column('agent_id', sa.CHAR(length=32), nullable=False),
    sa.Column('role', sa.VARCHAR(length=15), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('added_by_agent_id', sa.CHAR(length=32), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=False),
    sa.Column('kicked_by_agent_id', sa.CHAR(length=32), nullable=True),
    sa.Column('kicked_at', sa.DATETIME(), nullable=True),
    sa.Column('kick_reason', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'agent_id', name=op.f('uq_repo_agent'))
    )
    op.create_index(op.f('ix_repo_members_repo_id'), 'repo_members', ['repo_id'], unique=False)
    op.create_index(op.f('ix_repo_members_agent_id'), 'repo_members', ['agent_id'], unique=False)
    op.create_table('compute_jobs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('bounty_id', sa.VARCHAR(), nullable=False),
    sa.Column('repo_id', sa.CHAR(length=32), nullable=True),
    sa.Column('submission_id', sa.VARCHAR(), nullable=True),
    sa.Column('runner_id', sa.CHAR(length=32), nullable=True),
    sa.Column('execution_mode', sa.VARCHAR(length=12), nullable=False),
    sa.Column('test_command', sa.VARCHAR(length=500), nullable=False),
    sa.Column('code_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('code_branch', sa.VARCHAR(length=100), nullable=True),
    sa.Column('code_commit', sa.VARCHAR(length=40), nullable=True),
    sa.Column('env_vars', sqlite.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('assigned_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('exit_code', sa.INTEGER(), nullable=True),
    sa.Column('stdout_log', sa.TEXT(), nullable=True),
    sa.Column('stderr_log', sa.TEXT(), nullable=True),
    sa.Column('test_results', sqlite.JSON(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('is_audited', sa.BOOLEAN(), nullable=False),
    sa.Column('audit_job_id', sa.CHAR(length=32), nullable=True),
    sa.Column('audit_result', sa.VARCHAR(length=50), nullable=True),
    sa.Column('audit_mismatch_details', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('max_retries', sa.INTEGER(), nullable=False),
    sa.Column('next_retry_at', sa.DATETIME(), nullable=True),
    sa.Column('retry_backoff_factor', sa.FLOAT(), nullable=False),
    sa.Column('retry_base_delay_seconds', sa.INTEGER(), nullable=False),
    sa.Column('total_tests', sa.INTEGER(), nullable=False),
    sa.Column('passed_tests', sa.INTEGER(), nullable=False),
    sa.Column('failed_tests', sa.INTEGER(), nullable=False),
    sa.Column('skipped_tests', sa.INTEGER(), nullable=False),
    sa.Column('partial_pass_threshold', sa.FLOAT(), nullable=False),
    sa.Column('failure_severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('failure_reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('warnings', sqlite.JSON(), nullable=True),
    sa.Column('used_fallback', sa.BOOLEAN(), nullable=False),
    sa.Column('original_runner_id', sa.CHAR(length=32), nullable=True),
    sa.Column('requires_manual_review', sa.BOOLEAN(), nullable=False),
    sa.Column('service_endpoint', sa.VARCHAR(length=500), nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compute_jobs_status'), 'compute_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_compute_jobs_runner_id'), 'compute_jobs', ['runner_id'], unique=False)
    op.create_index(op.f('ix_compute_jobs_repo_id'), 'compute_jobs', ['repo_id'], unique=False)
    op.create_index(op.f('ix_compute_jobs_bounty_id'), 'compute_jobs', ['bounty_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('github_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('github_login', sa.VARCHAR(length=100), nullable=True),
    sa.Column('github_avatar', sa.VARCHAR(length=500), nullable=True),
    sa.Column('wechat_openid', sa.VARCHAR(length=100), nullable=True),
    sa.Column('wechat_nickname', sa.VARCHAR(length=100), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=False)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('runners',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('owner_user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('last_heartbeat_at', sa.DATETIME(), nullable=True),
    sa.Column('heartbeat_ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('cpu_cores', sa.INTEGER(), nullable=True),
    sa.Column('memory_gb', sa.INTEGER(), nullable=True),
    sa.Column('os_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('os_version', sa.VARCHAR(length=100), nullable=True),
    sa.Column('docker_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('labels', sqlite.JSON(), nullable=True),
    sa.Column('total_jobs_completed', sa.INTEGER(), nullable=False),
    sa.Column('total_jobs_failed', sa.INTEGER(), nullable=False),
    sa.Column('total_compute_seconds', sa.INTEGER(), nullable=False),
    sa.Column('total_earnings', sa.INTEGER(), nullable=False),
    sa.Column('reputation_score', sa.INTEGER(), nullable=False),
    sa.Column('audit_failures', sa.INTEGER(), nullable=False),
    sa.Column('is_banned', sa.BOOLEAN(), nullable=False),
    sa.Column('banned_reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('banned_at', sa.DATETIME(), nullable=True),
    sa.Column('current_job_id', sa.CHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('allowed_repo_ids', sqlite.JSON(), nullable=True),
    sa.Column('is_global', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runners_status'), 'runners', ['status'], unique=False)
    op.create_index(op.f('ix_runners_owner_user_id'), 'runners', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###
