import os
import subprocess
import tempfile
import json
from typing import List, Optional
from sqlmodel import Session, select
from persistence import Bounty, BountyStatus
from agenthub_protocol.path_utils import ensure_safe_path

class GitTreeService:
    def __init__(self, session: Session, storage_root: str):
        self.session = session
        self.storage_root = os.path.abspath(storage_root)

    def generate_mermaid(self, repo_name: str) -> str:
        """Generate a Mermaid flowchart for the repository's bounties."""
        statement = select(Bounty).where(Bounty.repo_name == repo_name)
        bounties = self.session.exec(statement).all()
        
        if not bounties:
            return "No tasks found for this repository."

        mermaid = ["flowchart LR"]
        
        # Styles
        mermaid.append("    classDef completed fill:#22c55e,stroke:#16a34a,color:#fff")
        mermaid.append("    classDef in_progress fill:#3b82f6,stroke:#2563eb,color:#fff")
        mermaid.append("    classDef open fill:#eab308,stroke:#ca8a04,color:#fff")
        mermaid.append("    classDef pending fill:#52525b,stroke:#3f3f46,color:#a1a1aa")
        mermaid.append("    classDef ready fill:#f97316,stroke:#ea580c,color:#fff")

        for b in bounties:
            # Node definition with status-based styling
            status = b.status
            style_class = "pending"
            if status == BountyStatus.COMPLETED.value:
                style_class = "completed"
            elif status == BountyStatus.IN_PROGRESS.value:
                style_class = "in_progress"
            elif status == BountyStatus.OPEN.value:
                style_class = "open"
            elif status == "ready_for_preparation":
                style_class = "ready"
            
            clean_title = b.title.replace('"', "'")
            mermaid.append(f'    node_{b.id}["{clean_title}"]::: {style_class}')
            
            # Dependencies
            if b.dependencies:
                for dep_id in b.dependencies:
                    mermaid.append(f"    node_{dep_id} --> node_{b.id}")

        return "\n".join(mermaid)

    def sync_repo_task_tree(self, repo_name: str, trusted_agent_id: str = "system"):
        """Update BOUNTY_TREE.md in the bare repository."""
        bare_repo_path = os.path.join(self.storage_root, repo_name)
        if not os.path.exists(bare_repo_path):
            return

        mermaid_code = self.generate_mermaid(repo_name)
        content = f"# Repository Task Tree\n\n```mermaid\n{mermaid_code}\n```\n\n*Last updated: {os.popen('date').read().strip()}*"

        work_dir = tempfile.mkdtemp(prefix="agenthub_tree_update_")
        try:
            # Clone and update
            subprocess.run(["git", "clone", bare_repo_path, work_dir], check=True, capture_output=True)
            
            file_path = os.path.join(work_dir, "BOUNTY_TREE.md")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)

            subprocess.run(["git", "add", "BOUNTY_TREE.md"], cwd=work_dir, check=True, capture_output=True)
            
            # Check if there are changes to commit
            status = subprocess.run(["git", "status", "--porcelain"], cwd=work_dir, capture_output=True, text=True)
            if not status.stdout.strip():
                return

            commit_msg = f"docs: update task tree visualization\n\n🤖 Generated by GitTreeService"
            subprocess.run(
                ["git", "commit", "-m", commit_msg],
                cwd=work_dir, check=True, capture_output=True,
                env={**os.environ, "GIT_AUTHOR_NAME": trusted_agent_id, "GIT_AUTHOR_EMAIL": f"{trusted_agent_id}@agenthub.dev",
                     "GIT_COMMITTER_NAME": trusted_agent_id, "GIT_COMMITTER_EMAIL": f"{trusted_agent_id}@agenthub.dev"}
            )
            
            subprocess.run(["git", "push", "origin", "main"], cwd=work_dir, check=True, capture_output=True)
        except Exception as e:
            print(f"Error syncing task tree: {e}")
        finally:
            import shutil
            shutil.rmtree(work_dir, ignore_errors=True)
