apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - job-migrate.yaml

images:
  - name: ghcr.io/opengit-dev/opengit-api-gateway
    newTag: REPLACED_BY_CI
  - name: ghcr.io/opengit-dev/opengit-observer-ui
    newTag: REPLACED_BY_CI

patches:
  - path: patches.yaml
